export const ALGERIAN_WILAYAS = [
    { value: "01", label: "01 - Adrar", name: "Adrar" },
    { value: "02", label: "02 - Chlef", name: "Chlef" },
    { value: "03", label: "03 - Laghouat", name: "Laghouat" },
    { value: "04", label: "04 - Oum El Bouaghi", name: "Oum El Bouaghi" },
    { value: "05", label: "05 - Batna", name: "Batna" },
    { value: "06", label: "06 - Béjaïa", name: "Béjaïa" },
    { value: "07", label: "07 - Biskra", name: "Biskra" },
    { value: "08", label: "08 - Béchar", name: "Béchar" },
    { value: "09", label: "09 - Blida", name: "Blida" },
    { value: "10", label: "10 - Bouira", name: "Bouira" },
    { value: "11", label: "11 - Tamanrasset", name: "Tamanrasset" },
    { value: "12", label: "12 - Tébessa", name: "Tébessa" },
    { value: "13", label: "13 - Tlemcen", name: "Tlemcen" },
    { value: "14", label: "14 - Tiaret", name: "Tiaret" },
    { value: "15", label: "15 - Tizi Ouzou", name: "Tizi Ouzou" },
    { value: "16", label: "16 - Alger", name: "Alger" },
    { value: "17", label: "17 - Djelfa", name: "Djelfa" },
    { value: "18", label: "18 - Jijel", name: "Jijel" },
    { value: "19", label: "19 - Sétif", name: "Sétif" },
    { value: "20", label: "20 - Saïda", name: "Saïda" },
    { value: "21", label: "21 - Skikda", name: "Skikda" },
    { value: "22", label: "22 - Sidi Bel Abbès", name: "Sidi Bel Abbès" },
    { value: "23", label: "23 - Annaba", name: "Annaba" },
    { value: "24", label: "24 - Guelma", name: "Guelma" },
    { value: "25", label: "25 - Constantine", name: "Constantine" },
    { value: "26", label: "26 - Médéa", name: "Médéa" },
    { value: "27", label: "27 - Mostaganem", name: "Mostaganem" },
    { value: "28", label: "28 - M'Sila", name: "M'Sila" },
    { value: "29", label: "29 - Mascara", name: "Mascara" },
    { value: "30", label: "30 - Ouargla", name: "Ouargla" },
    { value: "31", label: "31 - Oran", name: "Oran" },
    { value: "32", label: "32 - El Bayadh", name: "El Bayadh" },
    { value: "33", label: "33 - Illizi", name: "Illizi" },
    { value: "34", label: "34 - Bordj Bou Arreridj", name: "Bordj Bou Arreridj" },
    { value: "35", label: "35 - Boumerdès", name: "Boumerdès" },
    { value: "36", label: "36 - El Tarf", name: "El Tarf" },
    { value: "37", label: "37 - Tindouf", name: "Tindouf" },
    { value: "38", label: "38 - Tissemsilt", name: "Tissemsilt" },
    { value: "39", label: "39 - El Oued", name: "El Oued" },
    { value: "40", label: "40 - Khenchela", name: "Khenchela" },
    { value: "41", label: "41 - Souk Ahras", name: "Souk Ahras" },
    { value: "42", label: "42 - Tipaza", name: "Tipaza" },
    { value: "43", label: "43 - Mila", name: "Mila" },
    { value: "44", label: "44 - Aïn Defla", name: "Aïn Defla" },
    { value: "45", label: "45 - Naâma", name: "Naâma" },
    { value: "46", label: "46 - Aïn Témouchent", name: "Aïn Témouchent" },
    { value: "47", label: "47 - Ghardaïa", name: "Ghardaïa" },
    { value: "48", label: "48 - Relizane", name: "Relizane" },
    { value: "49", label: "49 - Timimoun", name: "Timimoun" },
    { value: "50", label: "50 - Bordj Badji Mokhtar", name: "Bordj Badji Mokhtar" },
    { value: "51", label: "51 - Ouled Djellal", name: "Ouled Djellal" },
    { value: "52", label: "52 - Béni Abbès", name: "Béni Abbès" },
    { value: "53", label: "53 - In Salah", name: "In Salah" },
    { value: "54", label: "54 - In Guezzam", name: "In Guezzam" },
    { value: "55", label: "55 - Touggourt", name: "Touggourt" },
    { value: "56", label: "56 - Djanet", name: "Djanet" },
    { value: "57", label: "57 - El M'Ghair", name: "El M'Ghair" },
    { value: "58", label: "58 - El Meniaa", name: "El Meniaa" }
];
