const fs = require('fs');

const filePath = 'i18n.js';
let content = fs.readFileSync(filePath, 'utf8');

const enBlock = `
            settings: {
                roles_title: "Roles & Permissions",
                roles_desc: "Manage access control profiles across the organization.",
                roles_create: "Create Custom Role",
                roles_system: "System Roles",
                roles_permissions_count: "permissions",
                roles_custom: "Custom Roles",
                roles_no_custom: "No custom roles yet.",
                roles_name_placeholder: "Role Name (e.g., Marketing Lead)",
                roles_desc_placeholder: "Description of what this role can do",
                roles_system_default: "System Default",
                roles_save: "Save Role",
                roles_edit: "Edit",
                roles_matrix: "Permission Matrix",
                roles_select_prompt: "Select a role to view permissions",
                roles_or_create: "Or create a new custom role"
            },
            modules: {
                overview: "Overview",
                financial: "Financial",
                sales: "Sales",
                inventory: "Inventory",
                warehouse: "Warehouse",
                dispatch: "Dispatch",
                procurement: "Procurement",
                manufacturing: "Manufacturing",
                hr: "Human Resources",
                projects: "Projects",
                customer: "Customers",
                users: "Users",
                settings: "Settings"
            },
            permissions: {
                "overview.read": "Read Overview",
                "financial.read": "Read Financials",
                "financial.view_costs": "View Costs",
                "financial.export": "Export Financials",
                "financial.manage_manual_transactions": "Manage Manual Transactions",
                "financial.approve_reports": "Approve Reports",
                "sales.read": "Read Sales",
                "sales.create": "Create Sale",
                "sales.update": "Update Sale",
                "sales.cancel": "Cancel Sale",
                "sales.delete": "Delete Sale",
                "sales.export": "Export Sales",
                "sales.view_customer_details": "View Customer Details",
                "inventory.read": "Read Inventory",
                "inventory.create_product": "Create Product",
                "inventory.update_product": "Update Product",
                "inventory.adjust_stock": "Adjust Stock",
                "inventory.view_cost": "View Cost",
                "inventory.view_supplier_data": "View Supplier Data",
                "inventory.export": "Export Inventory",
                "warehouse.read": "Read Warehouse",
                "warehouse.create": "Create Warehouse",
                "warehouse.update": "Update Warehouse",
                "warehouse.transfer_stock": "Transfer Stock",
                "warehouse.view_ledger": "View Ledger",
                "dispatch.read": "Read Dispatch",
                "dispatch.create_shipment": "Create Shipment",
                "dispatch.update_shipment": "Update Shipment",
                "dispatch.validate_shipment": "Validate Shipment",
                "dispatch.generate_label": "Generate Label",
                "dispatch.request_return": "Request Return",
                "dispatch.view_courier_financials": "View Courier Financials",
                "dispatch.export": "Export Dispatch",
                "procurement.read": "Read Procurement",
                "procurement.create_request": "Create Request",
                "procurement.approve_request": "Approve Request",
                "procurement.create_po": "Create PO",
                "procurement.update_po": "Update PO",
                "procurement.receive_goods": "Receive Goods",
                "procurement.view_supplier_metrics": "View Supplier Metrics",
                "procurement.export": "Export Procurement",
                "manufacturing.read": "Read Manufacturing",
                "manufacturing.manage_raw_materials": "Manage Raw Materials",
                "manufacturing.create_bom": "Create BOM",
                "manufacturing.update_bom": "Update BOM",
                "manufacturing.create_production_order": "Create Production Order",
                "manufacturing.start_production": "Start Production",
                "manufacturing.complete_stage": "Complete Stage",
                "manufacturing.complete_production": "Complete Production",
                "manufacturing.view_costs": "View Costs",
                "hr.read": "Read HR",
                "hr.create_employee": "Create Employee",
                "hr.update_employee": "Update Employee",
                "hr.manage_attendance": "Manage Attendance",
                "hr.manage_payroll": "Manage Payroll",
                "hr.approve_payroll": "Approve Payroll",
                "hr.view_salary": "View Salary",
                "hr.view_reports": "View Reports",
                "hr.manage_rewards": "Manage Rewards",
                "projects.read": "Read Projects",
                "projects.create": "Create Project",
                "projects.update": "Update Project",
                "projects.manage_tasks": "Manage Tasks",
                "projects.manage_milestones": "Manage Milestones",
                "projects.export": "Export Projects",
                "customer.read": "Read Customers",
                "customer.update": "Update Customer",
                "customer.view_risk": "View Risk",
                "customer.export": "Export Customers",
                "users.read": "Read Users",
                "users.create": "Create User",
                "users.update": "Update User",
                "users.deactivate": "Deactivate User",
                "users.assign_roles": "Assign Roles",
                "users.manage_permissions": "Manage Permissions",
                "security.view_sessions": "View Sessions",
                "security.force_logout": "Force Logout",
                "settings.read": "Read Settings",
                "settings.manage_profile": "Manage Profile",
                "settings.manage_company": "Manage Company",
                "settings.manage_integrations": "Manage Integrations",
                "settings.manage_courier_api": "Manage Courier API",
                "settings.manage_billing": "Manage Billing"
            },
`;

const arBlock = `
            settings: {
                roles_title: "الأدوار والصلاحيات",
                roles_desc: "إدارة ملفات التحكم في الوصول عبر المنظمة.",
                roles_create: "إنشاء دور مخصص",
                roles_system: "أدوار النظام",
                roles_permissions_count: "صلاحيات",
                roles_custom: "أدوار مخصصة",
                roles_no_custom: "لا توجد أدوار مخصصة بعد.",
                roles_name_placeholder: "اسم الدور (مثال: مدير المبيعات)",
                roles_desc_placeholder: "وصف لما يمكن لهذا الدور القيام به",
                roles_system_default: "افتراضي للنظام",
                roles_save: "حفظ الدور",
                roles_edit: "تعديل",
                roles_matrix: "مصفوفة الصلاحيات",
                roles_select_prompt: "حدد دوراً لعرض الصلاحيات",
                roles_or_create: "أو قم بإنشاء دور مخصص جديد"
            },
            modules: {
                overview: "نظرة عامة",
                financial: "المالية",
                sales: "المبيعات",
                inventory: "المخزون",
                warehouse: "المستودع",
                dispatch: "التوزيع والتوصيل",
                procurement: "المشتريات",
                manufacturing: "التصنيع والإنتاج",
                hr: "الموارد البشرية",
                projects: "المشاريع",
                customer: "العملاء",
                users: "المستخدمين",
                settings: "الإعدادات"
            },
            permissions: {
                "overview.read": "قراءة النظرة العامة",
                "financial.read": "قراءة المالية",
                "financial.view_costs": "عرض التكاليف",
                "financial.export": "تصدير المالية",
                "financial.manage_manual_transactions": "إدارة المعاملات اليدوية",
                "financial.approve_reports": "الموافقة على التقارير",
                "sales.read": "قراءة المبيعات",
                "sales.create": "إنشاء بيع",
                "sales.update": "تحديث البيع",
                "sales.cancel": "إلغاء البيع",
                "sales.delete": "حذف البيع",
                "sales.export": "تصدير المبيعات",
                "sales.view_customer_details": "عرض تفاصيل العميل",
                "inventory.read": "قراءة المخزون",
                "inventory.create_product": "إنشاء منتج",
                "inventory.update_product": "تحديث المنتجات",
                "inventory.adjust_stock": "تعديل المخزون",
                "inventory.view_cost": "عرض التكلفة",
                "inventory.view_supplier_data": "عرض بيانات المورد",
                "inventory.export": "تصدير المخزون",
                "warehouse.read": "قراءة المستودع",
                "warehouse.create": "إنشاء مستودع",
                "warehouse.update": "تحديث المستودع",
                "warehouse.transfer_stock": "نقل المخزون",
                "warehouse.view_ledger": "عرض الدفتر",
                "dispatch.read": "قراءة التوصيل",
                "dispatch.create_shipment": "إنشاء شحنة",
                "dispatch.update_shipment": "تحديث شحنة",
                "dispatch.validate_shipment": "تأكيد شحنة",
                "dispatch.generate_label": "توليد ملصق",
                "dispatch.request_return": "طلب إرجاع",
                "dispatch.view_courier_financials": "عرض مالية المندوب",
                "dispatch.export": "تصدير التوصيل",
                "procurement.read": "قراءة المشتريات",
                "procurement.create_request": "إنشاء طلب",
                "procurement.approve_request": "الموافقة على الطلب",
                "procurement.create_po": "إنشاء أمر شراء",
                "procurement.update_po": "تحديث أمر الشراء",
                "procurement.receive_goods": "استلام البضائع",
                "procurement.view_supplier_metrics": "عرض مقاييس المورد",
                "procurement.export": "تصدير المشتريات",
                "manufacturing.read": "قراءة التصنيع",
                "manufacturing.manage_raw_materials": "إدارة المواد الخام",
                "manufacturing.create_bom": "إنشاء قائمة المواد",
                "manufacturing.update_bom": "تحديث قائمة المواد",
                "manufacturing.create_production_order": "إنشاء أمر إنتاج",
                "manufacturing.start_production": "بدء الإنتاج",
                "manufacturing.complete_stage": "إنهاء مرحلة",
                "manufacturing.complete_production": "إنهاء الإنتاج",
                "manufacturing.view_costs": "عرض تكاليف التصنيع",
                "hr.read": "قراءة الموارد البشرية",
                "hr.create_employee": "إنشاء موظف",
                "hr.update_employee": "تحديث موظف",
                "hr.manage_attendance": "إدارة الحضور",
                "hr.manage_payroll": "إدارة الرواتب",
                "hr.approve_payroll": "الموافقة على الرواتب",
                "hr.view_salary": "عرض الراتب",
                "hr.view_reports": "عرض تقارير الموارد البشرية",
                "hr.manage_rewards": "إدارة المكافآت",
                "projects.read": "قراءة المشاريع",
                "projects.create": "إنشاء مشروع",
                "projects.update": "تحديث المشروع",
                "projects.manage_tasks": "إدارة المهام",
                "projects.manage_milestones": "إدارة المعالم",
                "projects.export": "تصدير المشاريع",
                "customer.read": "قراءة العملاء",
                "customer.update": "تحديث العميل",
                "customer.view_risk": "عرض المخاطر",
                "customer.export": "تصدير العملاء",
                "users.read": "قراءة المستخدمين",
                "users.create": "إنشاء مستخدم",
                "users.update": "تحديث مستخدم",
                "users.deactivate": "إلغاء تنشيط مستخدم",
                "users.assign_roles": "تعيين أدوار",
                "users.manage_permissions": "إدارة الصلاحيات",
                "security.view_sessions": "عرض الجلسات",
                "security.force_logout": "تسجيل خروج إجباري",
                "settings.read": "قراءة الإعدادات",
                "settings.manage_profile": "إدارة الملف الشخصي",
                "settings.manage_company": "إدارة الشركة",
                "settings.manage_integrations": "إدارة التكامل",
                "settings.manage_courier_api": "إدارة تكامل المندوبين",
                "settings.manage_billing": "إدارة الفواتير"
            },
`;

if (!content.includes('roles_title:')) {
    // English injection
    content = content.replace(
        /en:\s*\{\s*translation:\s*\{/,
        "en: {\\n        translation: {" + enBlock
    );

    // Arabic injection
    content = content.replace(
        /ar:\s*\{\s*translation:\s*\{/,
        "ar: {\\n        translation: {" + arBlock
    );

    fs.writeFileSync(filePath, content, 'utf8');
    console.log("Translation injection successful!");
} else {
    console.log("Translations already exist.");
}
